# Generated by Django 3.2 on 2021-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('age', models.TextField()),
                ('blod', models.TextField()),
                ('addres', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('zipcode', models.TextField()),
            ],
        ),
    ]
