# Generated by Django 3.2 on 2021-05-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coregister', '0004_remove_contact_uni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='query',
        ),
    ]
