# Generated by Django 3.2 on 2021-05-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregister', '0006_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(),
        ),
    ]
