# Generated by Django 3.2 on 2021-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregister', '0007_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='query',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='unique_id',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(default=True),
        ),
    ]
