# Generated by Django 3.2 on 2021-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregister', '0008_auto_20210504_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='unique_id',
            field=models.TextField(),
        ),
    ]
