# Generated by Django 3.2 on 2021-05-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregister', '0009_auto_20210504_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='op_date',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='status',
            field=models.TextField(default='waiting'),
        ),
    ]
