# Generated by Django 3.2 on 2021-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregister', '0010_auto_20210505_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='op_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='status',
            field=models.TextField(),
        ),
    ]
